Anton papin lesson 2 homework
AlexJavaGuru/java_1_wednesday_may pull request #11
Opened 2022-06-02 13:19 UTC by t3od0r

Whole homework for Lesson 2

2022-06-07 19:14 UTC, AlexJavaGuru requested changes

2022-06-08 09:56 UTC, t3od0r commented on src/main/java/lv/javaguru/student_anton_papin/lesson_2_homework/level_1/Scanner.java
> +        System.out.println( numberA / numberB );
Исправил все замечания.

2022-06-08 09:56 UTC, t3od0r commented on src/main/java/lv/javaguru/student_anton_papin/lesson_2_homework/level_6/NoSleepNoFocus.java
> +public class NoSleepNoFocus {public static void main(String[] args) {
Исправил все замечания.

2022-06-08 09:56 UTC, t3od0r commented on src/main/java/lv/javaguru/student_anton_papin/lesson_2_homework/level_7/CorrectDataTypes.java
> +public class CorrectDataTypes {public static void main(String[] args) {
Исправил все замечания.

2022-06-08 09:56 UTC, t3od0r commented on src/main/java/lv/javaguru/student_anton_papin/lesson_2_homework/level_7/SumTwoNumbers.java
> +public class SumTwoNumbers {public static void main(String[] args) {
Исправил все замечания.

2022-06-10 19:17 UTC, AlexJavaGuru approved these changes

2022-06-10 19:18 UTC, merged