Lesson 2: Homework tasks 1-14
AlexJavaGuru/java_1_wednesday_may pull request #21
Opened 2022-06-07 18:00 UTC by PecnayHeP

2022-06-07 19:52 UTC, AlexJavaGuru requested changes

2022-06-07 19:52 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_miroslavs_fjodorovs/lesson_2/Task_1.java
> +       System.out.println(firstNumber / secondNumber);
А если результат будет не целый? Тестировали? Может приведение типа надо сделать?

2022-06-07 19:59 UTC, PecnayHeP commented on src/main/java/lv/javaguru/student_miroslavs_fjodorovs/lesson_2/Task_1.java
> +       System.out.println(firstNumber / secondNumber);
Закоммитил изменение

2022-06-10 19:18 UTC, AlexJavaGuru approved these changes

2022-06-10 19:18 UTC, merged