Dmitri N lesson3 1/3
AlexJavaGuru/java_1_wednesday_may pull request #28
Opened 2022-06-09 20:42 UTC by dmitri1302

2022-06-09 20:43 UTC, dmitri1302 commented
Здравствуйте. Когда сделал пуш всё равно старый бранч прицепился :/

2022-06-14 18:13 UTC, AlexJavaGuru requested changes

2022-06-14 18:13 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task11_12_13/Roborename_demo.java
> +
Зачем столько лишних новых строк?

2022-06-14 18:13 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task11_12_13/Roborename_demo.java
> +
не надо каждую строчку писать с пропуском. Так можно логически разделить код на части, но не каждую строку.

2022-06-14 18:13 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task15/Phone.java
> +class Phone {
Надо поправить формат в классе. Отступы от края не правильные.

2022-06-14 18:13 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task18_19_20_21_22/Dog.java
> +    static final String RED = "\u001B[31m";
Это переменные, а переменные идет у нас сверху, перед конструктором.

2022-06-18 15:50 UTC, AlexJavaGuru requested changes
Все еще надо исправлять.

2022-06-18 15:50 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task18_19_20_21_22/Dog.java
>          print(BLACK);
Все еще не правильно. В чем смысл этого метода вообще? Он ничего не делает с новым цветом. Он должен поменять состояние объекта.

2022-06-18 15:50 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_dmitri_nekljudov/DmitriN_lesson_3/DmitriN_lesson_3_task18_19_20_21_22/Dog.java
>          print(YELLOW);
Все еще не правильно. В чем смысл этого метода вообще? Он ничего не делает с новым цветом. Он должен поменять состояние объекта.

2022-07-04 18:40 UTC, AlexJavaGuru submitted a review, later dismissed

2022-07-04 18:42 UTC, AlexJavaGuru approved these changes

2022-07-04 18:42 UTC, merged