Lesson_3
AlexJavaGuru/java_1_wednesday_may pull request #39
Opened 2022-06-15 01:21 UTC by SokolovsM

2022-06-18 18:00 UTC, AlexJavaGuru requested changes
Уберите цифры из классов. Чтобы удобно и быстро это делать - используйте Refactor -> Rename. Или Shift + F6

2022-06-19 11:00 UTC, SokolovsM commented on src/main/java/lv/javaguru/student_maksims_sokolovs/homework_lesson3/task12_13/Robot7.java
> +класс, если это не так, жду ваш комментарий.
Мне показалось, когда делал классы с одинаковым названием ,был какой-то конфликт. И почему то , не помню , чтобы говорили ,что нельзя в классах использовать цифры, пропустил этот момент, теперь точно запомню. Все исправлю.

2022-06-19 22:58 UTC, SokolovsM commented on src/main/java/lv/javaguru/student_maksims_sokolovs/homework_lesson3/task31/Product.java
> +        System.out.println("Discounted price is " + (regularPrice - (regularPrice*discount/100)));
ну вроде исправил

2022-06-29 15:58 UTC, AlexJavaGuru approved these changes

2022-06-29 15:59 UTC, merged