homework lesson 3
AlexJavaGuru/java_1_wednesday_may pull request #42
Opened 2022-06-15 13:40 UTC by lFabrio

Vladislav Katirlov, lesson 3, task 1-19

2022-06-30 21:10 UTC, AlexJavaGuru requested changes

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_4/Task14.java
> +class BookDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс BookDemo

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_4/Task15.java
> +    class PhoneDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс PhoneDemo

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_4/Task16.java
> +class CarDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс CarDemo

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_4/Task17.java
> +class BankAccountDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс BankAccountDemo

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_5/Task18.java
> +class DogDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс DogDemo

2022-06-30 21:10 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_5/Task19.java
> +class DogTwoDemo {
не нужно создавать внутренние классы. Сделайте отдельный класс DogTwoDemo

2022-07-05 11:03 UTC, lFabrio commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_3/level_5/Task19.java
> +class DogTwoDemo {
исправил все вышеперечисленное

2022-07-09 13:49 UTC, AlexJavaGuru approved these changes

2022-07-09 13:49 UTC, merged