Lesson 3
AlexJavaGuru/java_1_wednesday_may pull request #47
Opened 2022-06-18 15:53 UTC by IK777123

Lesson#3 ALL

2022-07-04 20:19 UTC, AlexJavaGuru requested changes

2022-07-04 20:19 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_3/level_1/RobotDemo.java
> +        robo1.sayHello();robo1.sayYourName();
В Java, мы не пишем несколько строк кода на одной строке...на то они и строки...кода =D После ; ничего не должно быть.

2022-07-04 20:19 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_3/level_7_senior/task_31/Product.java
> +    double result;
состояние result лишнее.

2022-07-04 20:19 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_3/level_7_senior/task_31/Product.java
> +    public double actualPrice(){
А этот метод точно правильно работает? Там вроде с процентах надо discount задавать...

2022-07-05 10:12 UTC, IK777123 commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_3/level_1/RobotDemo.java
> +        robo1.sayHello();robo1.sayYourName();
понятно!

2022-07-05 11:53 UTC, IK777123 commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_3/level_7_senior/task_31/Product.java
> +    double result;
убрал состояние result

2022-07-05 11:57 UTC, IK777123 commented
все исправленно

2022-07-09 13:54 UTC, AlexJavaGuru approved these changes

2022-07-09 13:55 UTC, merged