Student artjoms b homework4
AlexJavaGuru/java_1_wednesday_may pull request #49
Opened 2022-06-28 13:25 UTC by ArtjomsBogatirjovs

2022-07-04 21:24 UTC, AlexJavaGuru requested changes

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_1_intern/IsEven.java
> +class IsEven {
Как-то перемудрили для логики, где можно обойтись просто true/false

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/EqualOrDifferent.java
> +    boolean equalOrDifferent(int numberOne, int numberTwo) {
метод лучше назвать isEqual.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/EqualOrDifferentTest.java
> +        if (statement) System.out.println("Test - " + testName + " , Passed!");
Я вам очень рекомендую привыкнуть к стандартной форме написания if. Такое на code review не пропускают )

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/LargestNumber.java
> +            System.out.println("Number are equal");
Это лишняя инфа. По заданию просят найти большее число. Если подали одинаковые, просто верните любое. Оно будет работать в самом стандартном варианте.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/LargestNumberTest.java
> +        runner.numberOneBiggest((int) Math.floor(Math.random() * 100), (int) Math.floor(Math.random() * 100) - 101);
замените на статические цифры. Как человек который смотрит на тест, я не должен напрягаться чтобы понять, какие входные параметры.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/LargestNumberTest.java
> +        runner.numberTwoIsLargest((int) Math.floor(Math.random() * 100) - 101, (int) Math.floor(Math.random() * 100));
Данные для тестового сценария лучше размещать в самом методе.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/SmallestNumber.java
> +            System.out.println("Number are equal");
лишнее

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_2_intern/SmallestNumberTest.java
> +        runner.numberOneSmallest((int) Math.floor(Math.random() * 100) - 101, (int) Math.floor(Math.random() * 100));
то же самое, что и я другом тесте

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_3_junior/IncreasingNumbersTest.java
> +    void randomSequence() {
Можно сказать лишний тест.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_3_junior/ThreeNumbersEqual.java
> +        if (isNotEqual) {
а это нельзя сделать через else?

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_3_junior/ThreeNumbersEqual.java
> +        boolean isEqual = numOne == numTwo && numOne == numThree;
Флаги в программировании это такой себе стиль... они тут лишние, если подумать. Попробуйте все сделать через if

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_4_junior/Calculator.java
> +        return firstNumber / secondNumber;
Какой не точный Calculator ) не хотел бы таким делить.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_4_junior/Calculator.java
> +        return Math.max(firstNumber,secondNumber);
нельзя использовать Math тут. Напишите логику сами

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_4_junior/CalculatorTest.java
> +        calculatorTest.divideTest(10, 5);
Какие удобные числа ) а что если 9 разделить на 5?

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_4_junior/CalculatorTest.java
> +class CalculatorTest {
Переделывать не надо, но как проверяющему человеку, это очень сложно, когда данные где-то за пределами метода находятся. Надо смотреть тест, потом подниматься в main, смотреть какие числа там задаются...не очень стиль.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_6_middle/Stock.java
> +        if (currentPrice > maxPrice) {
if else?

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_6_middle/Stock.java
> +    int currentPrice;
почему не private? Сделайте private и напишите setter.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_6_middle/StockTest.java
> +        int result = Integer.parseInt(testMaxStock.getPriceInformation().replaceAll(".*\s(?=.*$)", ""));
зачем так сложно? Просто геттер сделайте.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_6_middle/StockTest.java
> +    void testMinPrice() {
супер переусложнённый тест. Напишите максимально просто. Не надо делать сплиты или что-то подобное. Просто геттайте значения объекта.  Будет на много понятнее написано.

2022-07-04 21:24 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_7_senior/Calculator.java
> +        return firstNumber / secondNumber;
Приведение типа? (double)?

2022-07-05 17:38 UTC, ArtjomsBogatirjovs commented on src/main/java/lv/javaguru/student_artjomsb_homework/homework4/level_4_junior/CalculatorTest.java
> +class CalculatorTest {
Хорошо, буду работать над этим и в методе писать

2022-07-09 14:16 UTC, AlexJavaGuru approved these changes

2022-07-09 14:17 UTC, merged