Student eugene sheinin lesson 4
AlexJavaGuru/java_1_wednesday_may pull request #57
Opened 2022-07-06 09:11 UTC by eugene-favor

Здравствуйте, домашнее задание по if statement..

2022-07-10 19:36 UTC, AlexJavaGuru requested changes

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +//        System.out.println("Enter number for positive or negative checking please :");
Зачем тут столько комментариев?

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +    String positiveOrNegative(int number) {
Этот метод должен возвращать true - если положительное и false, если отрицательное. А называться он должен - isPositive.

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        System.out.println(result);
Выводить на консоль результат не нужно. Надо просто вернуть

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +    String oddOrEven (int number) {
Это бинарная логика. Так же как и с positive/negative

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        System.out.println("This number is: " + result);
Выводить не нужно

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        if (number1 != number2 ) {
зачем два условия? Этот метод делается в три строки
if (number1 > number2) {
return number1;
}
return number2;

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +    int getMinNumber(int number1, int number2) {
То же самое, что и с getMax

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        boolean equal = true;
Нам не нужно делать флаги для этой логики. Этот метод делается в три строчки.

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        String result = "equal";
Эта переменная лишняя

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        int max = number1;
зачем вы делаете это действие? Попробуйте обойтись без него

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_4/Calculator.java
> +        int max = firstNumber;
эта переменная не нужна. Делайте return в теле if,

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_4/Calculator.java
> +        int max = number1;
лишняя переменная.

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_6/Stock.java
> +    public static void main(String[] args) {
Метода main не должно быть в классе Stock.

2022-07-10 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_6/Stock.java
> +        if(this.minPrice > newPrice) {
эти два условия надо написать через if else if, а не через два отдельных if-a

2022-07-14 08:22 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +//        System.out.println("Enter number for positive or negative checking please :");
убрал

2022-07-14 08:22 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        System.out.println(result);
поправил

2022-07-14 08:22 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +    String oddOrEven (int number) {
поправил

2022-07-14 08:22 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        System.out.println("This number is: " + result);
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        boolean equal = true;
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        String result = "equal";
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_1_2_3/NumberChecker.java
> +        int max = number1;
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_4/Calculator.java
> +        int max = firstNumber;
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_4/Calculator.java
> +        int max = number1;
поправил

2022-07-14 08:23 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_4/level_6/Stock.java
> +        if(this.minPrice > newPrice) {
поправил

2022-07-14 17:00 UTC, AlexJavaGuru approved these changes

2022-07-14 17:18 UTC, merged