Dd lesson4 lvl 1-5
AlexJavaGuru/java_1_wednesday_may pull request #60
Opened 2022-07-07 11:24 UTC by Wanxezar

2022-07-15 20:31 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_3/Task9.java
> +        int A = scanner.nextInt();
Никогда не пишите переменные с большой буквы.

2022-07-15 20:33 UTC, AlexJavaGuru requested changes
Надо поправить

2022-07-20 15:12 UTC, Wanxezar commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_3/Task9.java
> +        int A = scanner.nextInt();
Updated

2022-07-20 15:12 UTC, Wanxezar commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_3/Task8.java
> +        if(A==B && A==C){
Updated

2022-07-20 15:12 UTC, Wanxezar commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_4/Calculator.java
> +    public int maxOfThreeNumbers(int first, int second, int third) {
Updated. Но надеюсь, я Вас правильно понял

2022-07-22 21:12 UTC, AlexJavaGuru requested changes

2022-07-22 21:12 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_4/Calculator.java
> +    public int maxOfThreeNumbers(int first, int second, int third) {
О нет, совсем не правильно. Там всего 3 ретурна должно быть. Или firstNumber, или secondNumber, или thirdNumber

2022-07-22 21:12 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_4/Calculator.java
> +    public int maxOfThreeNumbers(int first, int second, int third) {
Подумайте. Там всё элементарно. Три условия if всего

2022-07-23 17:53 UTC, Wanxezar commented on src/main/java/lv/javaguru/student_daniels_demishins/hw_lesson_4/lvl_4/Calculator.java
> +    public int maxOfThreeNumbers(int first, int second, int third) {
Updated

2022-07-26 09:39 UTC, AlexJavaGuru approved these changes

2022-07-26 09:40 UTC, AlexJavaGuru approved these changes

2022-07-26 09:40 UTC, merged