Student eugene sheinin lesson 6 part 1 1-25 tasks
AlexJavaGuru/java_1_wednesday_may pull request #65
Opened 2022-07-09 11:52 UTC by eugene-favor

Здравствуйте, 
пока то, что успел по lesson 6 1-25 таск
Остальное надеюсь успею докинуть..
может в отдельном пулл реквесте.

2022-07-09 17:36 UTC, eugene-favor commented
Запушил пока не проверили продолжение по крестики нолики..26 -30 таски

2022-07-10 14:12 UTC, eugene-favor commented
Запушил таски 32-33. 
Искустшенный интеллект с каждым ходом проверяет выигрышную позицию для оппента, и если такова есть, делает ход на ее место (перекрывает ход).

2022-07-18 19:36 UTC, AlexJavaGuru requested changes

2022-07-18 19:36 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_6/level_3/ArrayService.java
> +    public static void main(String[] args) {
тут не должно быть main метода.

2022-07-22 21:12 UTC, AlexJavaGuru approved these changes

2022-07-22 21:13 UTC, merged