Vladislavs katirlovs lesson 5
AlexJavaGuru/java_1_wednesday_may pull request #74
Opened 2022-07-15 23:02 UTC by lFabrio

lesson 5 full

2022-07-28 16:47 UTC, AlexJavaGuru requested changes

2022-07-28 16:47 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_4/level_4/Calculator.java
> +        if (firstNumber > secondNumber) {
Упростите метод. Он выглядит очень страшно. много лишних условий. Должно быть всего 3 ретурна (по одному на одно значение)

2022-07-28 16:47 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_4/level_4/CalculatorTest.java
> +    public void divTest() {
попробуйте тут использовать числа, чтобы не делилось без остатка...

2022-07-28 16:47 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_5/level_2/Task15.java
> +        array[0] = array[0] + 2;
Это надо делать через циклы

2022-07-28 16:47 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_5/level_2/Task15.java
> +        array[0] = random.nextInt(10);
через циклы

2022-08-03 12:46 UTC, lFabrio commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_4/level_4/CalculatorTest.java
> +    public void divTest() {
я случайно запушил вместе в 5м лессоном, свой 4й без исправлений. Вы уже заапрувили весь 4й, там все в порядке, можно ли как то удалить в этого пулл реквеста 4й лессон?

2022-08-03 12:46 UTC, lFabrio commented on src/main/java/lv/javaguru/student_vladislavs_katirlovs/lesson_4/level_4/Calculator.java
> +        if (firstNumber > secondNumber) {
я случайно запушил вместе в 5м лессоном, свой 4й без исправлений. Вы уже заапрувили весь 4й, там все в порядке, можно ли как то удалить в этого пулл реквеста 4й лессон?

2022-08-06 21:19 UTC, AlexJavaGuru approved these changes

2022-08-06 21:19 UTC, merged