Rodions Full Lesson 6, but Tic Tac Toe w/o AI
AlexJavaGuru/java_1_wednesday_may pull request #76
Opened 2022-07-20 09:45 UTC by Somalo99

2022-07-28 19:41 UTC, AlexJavaGuru requested changes

2022-07-28 19:41 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_rodions_pismennijs/lesson_6/level_3/ArrayService.java
> +            if (i == numberToSearch) {
тут что-то не правильное. Если i == numberToSearch? Я думал мы в массиве должны искать числа.

2022-07-28 19:41 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_rodions_pismennijs/lesson_6/level_3/ArrayService.java
> +            if (j == numberToSearch) {
то же самое. Как вы тестили это?

2022-07-28 19:41 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_rodions_pismennijs/lesson_6/level_3/ArrayServiceTest.java
> +        int[] array = {1, 2, 3, 4, 5};
а я вижу, как вы тестили...подайте чуть более рандомные значения....

2022-08-02 22:38 UTC, Somalo99 commented
Не вижу тут ошибки, я ведь использую enhanced for или как он там называется. Он же и так in array чекает числа. Или я что-то не понял?

2022-08-03 14:29 UTC, AlexJavaGuru commented
Да, всё правильно. Мой косяк. Конечно лучше всего использовать полные названия переменных. Типа number, item, что-то такое.

2022-08-03 14:29 UTC, AlexJavaGuru approved these changes

2022-08-03 14:29 UTC, merged