Student eugene sheinin lesson 7
AlexJavaGuru/java_1_wednesday_may pull request #84
Opened 2022-08-01 17:37 UTC by eugene-favor

Здравствуйте, домашняя работа номер 7.

2022-08-16 15:49 UTC, AlexJavaGuru requested changes

2022-08-16 15:49 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_6/Palindrome.java
> +        //System.out.println(Arrays.toString(" fuck off".toCharArray()));
??

2022-08-16 15:49 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_6/Palindrome.java
> +    public static void main(String[] args) {
Метод main тут не нужен.

2022-08-16 15:49 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_7/UserEntityRepository.java
> +class UserEntityRepository {
Отформатируйте весь класс

2022-08-16 15:49 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_7/WordService.java
> +        for (int count =0; count < wordCounts.length; count++) {
может можно этот поиск максимума тоже закинуть в отдельный метод?

2022-08-16 20:31 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_6/ArrayCopy.java
> +        int[] newArray = new int[this.getFilteredNumberCount(in, numberFrom, numberTo)];
Вынес

2022-08-16 20:32 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_6/Palindrome.java
> +        //System.out.println(Arrays.toString(" fuck off".toCharArray()));
Прошу прощения. Не помню как там оказалось )))

2022-08-16 20:32 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_7/UserEntityRepository.java
> +class UserEntityRepository {
отформатировал

2022-08-16 20:32 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_6/Palindrome.java
> +    public static void main(String[] args) {
убрал

2022-08-16 20:32 UTC, eugene-favor commented on src/main/java/lv/javaguru/student_eugene_sheinin/homework/lesson_7/level_7/WordService.java
> +        for (int count =0; count < wordCounts.length; count++) {
закинул

2022-08-20 09:32 UTC, AlexJavaGuru approved these changes

2022-08-20 09:33 UTC, merged