Ivan k lesson 6
AlexJavaGuru/java_1_wednesday_may pull request #88
Opened 2022-08-04 10:15 UTC by IK777123

Ivan k lesson 6 ALL

2022-08-16 17:27 UTC, AlexJavaGuru requested changes

2022-08-16 17:27 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_ivan_k/homework/lesson_6/level_3junior/task_13/ArrayService.java
> +    public void printResultofFounding(boolean isFound) {
это лишний метод

2022-08-16 17:27 UTC, AlexJavaGuru commented on src/main/java/lv/javaguru/student_vadim_zamjatin/lesson_4/Calculator/CalculatorTest.java
> +    package main.java.lv.javaguru.student_vadim_zamjatin.lesson_4.Calculator;
а это что тут делает?

2022-08-20 13:28 UTC, IK777123 commented
все исправил
прошу проверить

2022-08-21 14:53 UTC, AlexJavaGuru submitted a review, later dismissed

2022-08-21 14:55 UTC, AlexJavaGuru approved these changes

2022-08-21 14:55 UTC, merged